import Head from "next/head";
import Main from "../components/Main";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-4 lg:mx-24">
        <Main />
      </div>
    </div>
  );
}
