import Head from "next/head";
import { useEffect } from "react";
import Main from "../components/Main";

export default function Home() {
  // useEffect(() => {
  //   localStorage.setItem("isNormal", false);
  // }, []);

  return (
    <div className="">
      <Head>
        <title>CBS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-4 lg:mx-24">
        <Main />
      </div>
    </div>
  );
}
